name: tansansu
description:  Carbonated Thinking

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: 
permalink: /:year/:month/:title/
owner: 
    name: tansansu
    twitter: #
    github: tansansu
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Asia/Seoul